import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {ToDoProvider} from './components/ToDoContext.jsx' 
import Header from './components/Header.jsx'
import ToDoList from './components/ToDoList'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ToDoProvider>
          <Header/>
          <ToDoList/>
        </ToDoProvider>
        
      </main>

    </div>
  )
}
